# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/ki18n' : '@latest'
    'frameworks/kcontacts' : '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'pim/kmime' : '@same'
    'pim/kpkpass' : '@same'

Options:
  # exclude large generated files that hang cppcheck
  cppcheck-ignore-files:
  - 'src/lib/knowledgedb/countrydb.cpp'
  - 'src/lib/knowledgedb/countrydb_data.cpp'
  - 'src/lib/knowledgedb/trainstationdb.cpp'
  - 'src/lib/knowledgedb/trainstationdb_data.cpp'
