# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n' : '@latest-kf6'
    'frameworks/kcontacts' : '@latest-kf6'
    'frameworks/kcalendarcore' : '@latest-kf6'
    'frameworks/kcodecs' : '@latest-kf6'
    'pim/kmime' : '@same'
    'pim/kpkpass' : '@same'
    'third-party/zxing-cpp': '@latest'

Options:
  # exlucde large generated files from cppcheck, takes way to long to run
  cppcheck-ignore-files:
  - 'src/lib/knowledgedb/trainstationdb.cpp'
  - 'src/lib/knowledgedb/trainstationdb_data.cpp'
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
